name: Keep Streamlit App Awake

on:
  schedule:
    - cron: "0 */6 * * *"   # jalan tiap 6 jam
  workflow_dispatch:         # bisa dijalankan manual dari tab Action

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl -s https://locoutproject-dewiadam.streamlit.app/ > /dev/null

